version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    container_name: server1
    build: .
    ports:
      - 8080:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin1
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql1
      #PMA_USER: root
      #PMA_PASSWORD: root
    ports:
      - 8081:80
    
  php:
    image: php:apache
    volumes:
      - './:/var/www/html'
    ports:
      - 80:80
    command: >
      sh -c "docker-php-ext-install mysqli"

volumes:
  mysql_data:
